### ISSUE TITLE
Corporate sponsoring, crowdfounding

### ISSUE THREAD

**Issue by jpic** [mjtamlyn/django-adapters#31]
Hi all!

I'm convinced this project is the future, should we start a donation campaign and recruit a hacker like 3 months to make a release of this ?

Would this help make this an actual ongoing project ?

Best regards

**Comment by mjtamlyn** [comment]
It's definitely an option I have been considering. I have some imminent changes in my employment situation and once that dust has settled I hope to be able to revisit this project properly.

**Comment by jpic** [comment]
Awesome, I know it's not much but we're not mozilla is our company is brand new and i'm probably going to make a fool of myself again but here goes, we can contribute in 10k, and double it for ElementUI support.

**Comment by mjtamlyn** [comment]
That's definitely an attractive offer, and one which I'll have to give some thought. I won't have tons of time to consider it before April, but perhaps we can set up an initial chat about the project then? Drop me an email 😃

**Comment by jpic** [comment]
Sure, should I also start prospecting github for other hacker businesses who could be interrested in adding up ? Ie. WiserTogether who maintains django-remote-forms ? It would be great if you could estimate how much you need ie. for 3 months.

Email copy, ftr:
> 
> Hello Marc,
> 
> Right now I have 10k secure for your project in the bank account, but talk again by the end of the month and it'll be even better.
> 
> Please send your first bill along with your IBAN to:
> 
> YourLabs Business Service
> 19A Rue de la Combe Jaillou
> 16730 Fleac, France
> 
> All i hope is that we have a usable product before our budget is depleted.
> 
> You have my complete trust.
> 
> Best regards

**Comment by jpic** [comment]
Given the beast it looks like we're going to deal with, i'd throw in an estimate of 300 manhours, in which case, i think we need to find another 10k.

**Comment by jpic** [comment]
All you have to do is send a quote to the address above and we'll return it signed as possible.

Best of luck <3
