### ISSUE TITLE
"Dynamic" schemas

### ISSUE THREAD

**Issue by jpic** [mjtamlyn/django-adapters#32]
I don't know what would be the proper title for this issue, but it's about something i've been doing manually over and over again most of my life.

Here goes: http://facond.readthedocs.io/en/master/tutorial.html#what-this-is

Do you think it's still time we had something like that to the specs ?

Surely, this will make this app more valuable than competiting libs, IMHO.

**Comment by mjtamlyn** [comment]
Having clean programmatic access to create adapters is definitely a design goal, but I'm not sure that we want to build a particular implementation of a model for them just yet.

I've personally built several implementations in my time, and they often have different domain specific features (for example the form actually is part of one page of a complex questionnaire, and has supporting imagery and rich text content with fields...). If we get the API right it should be easier to build such libraries against it. I'm not against a reference implementation at some point, but it should be separate.

**Comment by jpic** [comment]
Note that schematics has a similar feature: http://schematics.readthedocs.io/en/latest/usage/exporting.html#exporting
