### ISSUE TITLE
Consider renaming to python-adapters, have adapters.django

### ISSUE THREAD

**Issue by jpic** [mjtamlyn/django-adapters#34]
From what I understand of the specs, this lib will be completely python generic, expect for the part where we load or save data in Django models, or generate a schema based on a Django model.

If this is correct, should we consider a rename of the project and aim for loose coupling with Django rather than tight coupling ?

**Comment by mjtamlyn** [comment]
Loose coupling may well be a good design goal, although this would be far from the first project for a `0.X` version to be quite Django specific, and future editions pull the pieces apart. (Factory boy & Graphene are two libs which spring to mind).
