### ISSUE TITLE
Weekly hangout !

### ISSUE THREAD

**Issue by jpic** [mjtamlyn/django-adapters#38]
Hi all !

I think it would be cool to have a weekly hangout session where we can discuss live and synchronize our brains to help going in the same direction.

I know time zones want to make it impossible, but if you want to try anyway please leave your timezone and usual availabilities in this issue ;)

**Comment by mjtamlyn** [comment]
This only makes sense if we get multiple people actively working on it again. Right now that's not the case, so I'm going to close this issue.

**Comment by jpic** [comment]
I understand ;)

FTR, another way to have a 24/7 ongoing 3-month hackaton, lift mountains as a team ;)

https://tech.people-doc.com/welcome-to-the-virtual-open-space.html
